apps/dashboard/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.dashboard.views import TrackListView, TrackCreateView, TrackUpdateDetailView, TrackCreatePageView, \
    TrackUpdateView, TrackDeleteView

app_name = 'dashboard'
urlpatterns = [
    path('', login_required(TrackListView.as_view()), name='list'),
    path('create/', login_required(TrackCreateView.as_view()), name='create'),
    path('update/<int:pk>/', login_required(TrackUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/', login_required(TrackDeleteView.as_view()), name='delete'),
    path('update-page/<int:pk>/', login_required(TrackUpdateDetailView.as_view()), name='update-page'),
    path('create-page/', login_required(TrackCreatePageView.as_view()), name='create-page'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.dashboard.urls')),
    path('', include('apps.authentication.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/dashboard/models.py
from django.db import models

from config.models import BaseModel


class Track(BaseModel):
    order_num = models.CharField(max_length=20, null=True, blank=True)
    box = models.CharField(max_length=20, null=True, blank=True)
    container = models.TextField(null=True, blank=True)
    shipper = models.TextField(null=True, blank=True)
    cargo = models.TextField(null=True, blank=True)
    customer = models.TextField(null=True, blank=True)
    dispatch = models.DateField(null=True, blank=True)
    load_date = models.DateField(null=True, blank=True)
    agent = models.TextField(null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    consignee = models.TextField(null=True, blank=True)
    price = models.BigIntegerField(null=True, blank=True)
    client_price = models.BigIntegerField(null=True, blank=True)
    extra_expense = models.BigIntegerField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)

    WAITING = 0
    GIVEN = 1
    STATUS_CHOICE = [
        (WAITING, 'Waiting'),
        (GIVEN, 'Given')
    ]
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=WAITING, null=True, blank=True)

    class Meta:
        db_table = 'Track'

apps/dashboard/views.py
from django.db.models import Sum, Q
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, TemplateView, DeleteView

from apps.dashboard.models import Track
from datetime import datetime

from config.utils.price_or_none import none_zero


class TrackListView(ListView):
    model = Track
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        page_number = self.request.GET.get('page', 1)
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        tracks_count = Track.objects.all().count()
        price = none_zero(Track.objects.aggregate(price=Sum('price')).get('price'))
        client_price = none_zero(Track.objects.aggregate(client_price=Sum('client_price')).get('client_price'))
        extra_expense = none_zero(Track.objects.aggregate(extra_expense=Sum('extra_expense')).get('extra_expense'))

        search_query = self.request.GET.get('global-search')
        if search_query:
            tracks = Track.objects.filter(
                Q(order_num__icontains=search_query) |
                Q(box__icontains=search_query) |
                Q(container__icontains=search_query) |
                Q(shipper__icontains=search_query) |
                Q(cargo__icontains=search_query) |
                Q(customer__icontains=search_query) |
                Q(dispatch__icontains=search_query) |
                Q(load_date__icontains=search_query) |
                Q(agent__icontains=search_query) |
                Q(location__icontains=search_query) |
                Q(consignee__icontains=search_query) |
                Q(status__icontains=search_query)).order_by('-id')
        else:
            tracks = self.model.objects.all().order_by('-id')
        # paginator = Paginator(tracks, 10)
        # page_obj = paginator.get_page(page_number)
        # context['tracks'] = page_obj
        context['tracks'] = tracks
        context['totals'] = {
            'tracks_count': tracks_count,
            'price': price,
            'client_price': client_price,
            'extra_expense': extra_expense
        }
        return context


class TrackCreateView(CreateView):
    model = Track
    fields = ['order_num', 'box', 'container', 'shipper', 'cargo', 'customer', 'dispatch', 'load_date', 'agent',
              'location', 'consignee', 'price', 'client_price', 'extra_expense', 'status', 'comment', ]
    success_url = reverse_lazy('dashboard:list')

    def form_valid(self, form):
        form.instance.created_at = datetime.now()
        form.instance.updated_at = datetime.now()
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.groups.first().name == 'office_manager':
            return redirect('dashboard:list')
        return super().dispatch(request, *args, **kwargs)


class TrackUpdateView(UpdateView):
    model = Track
    fields = ['order_num', 'box', 'container', 'shipper', 'cargo', 'customer', 'dispatch', 'load_date', 'agent',
              'location', 'consignee', 'price', 'client_price', 'extra_expense', 'status', 'comment', ]
    success_url = reverse_lazy('dashboard:list')

    def post(self, request, **kwargs):
        instance = self.get_object()
        request.POST = request.POST.copy()
        if request.user.groups.first().name != 'office_pro_manager':
            request.POST['price'] = instance.price
            request.POST['client_price'] = instance.client_price
            request.POST['extra_expense'] = instance.extra_expense
        return super(TrackUpdateView, self).post(request, **kwargs)

    def form_valid(self, form):
        form.instance.updated_at = datetime.now()
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class TrackDeleteView(DeleteView):
    model = Track
    success_url = reverse_lazy('dashboard:list')


class TrackUpdateDetailView(DetailView):
    model = Track
    template_name = 'retrieve-update.html'


class TrackCreatePageView(TemplateView):
    template_name = 'retrieve-create.html'

    def dispatch(self, request, *args, **kwargs):
        group = request.user.groups.first()
        if group:
            if group.name == 'office_manager':
                return redirect('dashboard:list')
            return super().dispatch(request, *args, **kwargs)
        else:
            return render(request, '404.html', {'message': 'You are not allowed!'})

apps/dashboard/templates/retrieve-create.html
{% extends 'layout.html' %}

{% block title %}
    Add tracking
{% endblock %}
{% block content %}
    {#    {% if user.is_authenticated %}#}
    <div class="content-page">
        <div class="content border-primary-custom">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <form method="post" action="{% url 'dashboard:create' %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="order_num">Order Number</label>
                                    <input class="form-control" id="order_num" name="order_num"
                                           type="text" value="{{ track.order_num }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="box">Box</label>
                                    <input class="form-control" id="box" name="box"
                                           type="text" value="{{ track.box }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="container">Container</label>
                                    <input class="form-control" id="container" name="container"
                                           type="text" value="{{ track.container }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="shipper">Shipper</label>
                                    <input class="form-control" id="shipper" name="shipper"
                                           type="text" value="{{ track.shipper }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="cargo">Cargo</label>
                                    <input class="form-control" id="cargo" name="cargo"
                                           type="text" value="{{ track.cargo }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="customer">Customer</label>
                                    <input class="form-control" id="customer" name="customer"
                                           type="text" value="{{ track.customer }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="dispatch">Dispatch</label>
                                    <input class="form-control" id="dispatch" name="dispatch"
                                           type="date" value="{{ track.dispatch|date:"Y-m-d" }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="load_date">Load Date</label>
                                    <input class="form-control" id="load_date" name="load_date"
                                           type="date" value="{{ track.load_date|date:"Y-m-d" }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="agent">Agent</label>
                                    <input class="form-control" id="agent" name="agent"
                                           type="text" value="{{ track.agent }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="location">Location</label>
                                    <input class="form-control" id="location" name="location"
                                           type="text" value="{{ track.location }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="consignee">Consignee</label>
                                    <input class="form-control" id="consignee" name="consignee"
                                           type="text" value="{{ track.consignee }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="status">Status</label>
                                    <select name="status" id="status" class="form-control">
                                        <option value="0">Waiting</option>
                                        <option value="1">Given</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="price">Price</label>
                                    <input class="form-control" id="price" name="price"
                                           type="number" value="{{ track.price }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="client_price">Client Price</label>
                                    <input class="form-control" id="client_price" name="client_price"
                                           type="number" value="{{ track.client_price }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="extra_expense">Extra Expense</label>
                                    <input class="form-control" id="extra_expense" name="extra_expense"
                                           type="number" value="{{ track.extra_expense }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="comment">Comment</label>
                                    <textarea class="form-control" id="comment" name="comment"
                                              rows="3">{{ track.comment }}</textarea>
                                </div>
                                <div class="form-group col-md-12">
                                    <a class="btn btn-secondary" href="{% url 'dashboard:list' %}">Back</a>
                                    <input type="submit" class="btn btn-primary" value="Add">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    {% else %}#}
    {#        <h2 class="text-center mt-3">Please Sign</h2>#}
    {#    {% endif %}#}
{% endblock %}

apps/dashboard/templates/retrieve-update.html
{% extends 'layout.html' %}

{% block title %}
    Update tracking
{% endblock %}
{% block content %}
    {#    {% if user.is_authenticated %}#}
    <div class="content-page">
        <div class="content border-primary-custom">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <form method="post" action="{% url 'dashboard:update' track.id %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="order_num">Order Number</label>
                                    {% if track.order_num %}
                                        <input class="form-control" id="order_num" name="order_num"
                                               type="text" value="{{ track.order_num }}">
                                    {% else %}
                                        <input class="form-control" id="order_num" name="order_num"
                                               type="text" value="">
                                    {% endif %}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="box">Box</label>
                                    {% if track.box %}
                                        <input class="form-control" id="box" name="box"
                                               type="text" value="{{ track.box }}">
                                    {% else %}
                                        <input class="form-control" id="box" name="box"
                                               type="text" value="">
                                    {% endif %}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="container">Container</label>
                                    <input class="form-control" id="container" name="container"
                                           type="text" value="{{ track.container }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="shipper">Shipper</label>
                                    <input class="form-control" id="shipper" name="shipper"
                                           type="text" value="{{ track.shipper }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="cargo">Cargo</label>
                                    <input class="form-control" id="cargo" name="cargo"
                                           type="text" value="{{ track.cargo }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="customer">Customer</label>
                                    <input class="form-control" id="customer" name="customer"
                                           type="text" value="{{ track.customer }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="dispatch">Load Date</label>
                                    <input class="form-control" id="dispatch" name="dispatch"
                                           type="date" value="{{ track.dispatch|date:"Y-m-d" }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="load_date">Load Date</label>
                                    <input class="form-control" id="load_date" name="load_date"
                                           type="date" value="{{ track.load_date|date:"Y-m-d" }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="agent">Agent</label>
                                    <input class="form-control" id="agent" name="agent"
                                           type="text" value="{{ track.agent }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="location">Location</label>
                                    <input class="form-control" id="location" name="location"
                                           type="text" value="{{ track.location }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="consignee">Consignee</label>
                                    <input class="form-control" id="consignee" name="consignee"
                                           type="text" value="{{ track.consignee }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="status">Status</label>
                                    <select name="status" id="status" class="form-control">
                                        {% if track.status == 0 %}
                                            <option selected value="0">Waiting</option>
                                            <option value="1">Given</option>
                                        {% else %}
                                            <option value="0">Waiting</option>
                                            <option selected value="1">Given</option>
                                        {% endif %}
                                    </select>
                                </div>
                                {% if user.groups.first.name != 'office_manager' %}
                                    <div class="form-group col-md-6">
                                        <label for="price">Price</label>
                                        {% if track.price %}
                                            <input class="form-control" id="price" name="price"
                                                   type="text" value="{{ track.price }}">
                                        {% else %}
                                            <input class="form-control" id="price" name="price"
                                                   type="text" value="">
                                        {% endif %}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="client_price">Client Price</label>
                                        {% if track.client_price %}
                                            <input class="form-control" id="price" name="client_price"
                                                   type="text" value="{{ track.client_price }}">
                                        {% else %}
                                            <input class="form-control" id="price" name="client_price"
                                                   type="text" value="">
                                        {% endif %}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="extra_expense">Extra Expense</label>
                                        {% if track.extra_expense %}
                                            <input class="form-control" id="price" name="extra_expense"
                                                   type="text" value="{{ track.extra_expense }}">
                                        {% else %}
                                            <input class="form-control" id="price" name="extra_expense"
                                                   type="text" value="">
                                        {% endif %}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="comment">Comment</label>
                                        {% if track.comment %}
                                            <textarea class="form-control" id="comment" name="comment"
                                                  rows="3">{{ track.comment }}</textarea>
                                        {% else %}
                                            <textarea class="form-control" id="comment" name="comment"
                                                  rows="3"></textarea>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <a class="btn btn-secondary" href="{% url 'dashboard:list' %}">Back</a>
                                <input type="submit" class="btn btn-warning" value="Update">
                            </div>
                        </form>
                        {% if user.groups.first.name != 'office_manager' %}
                            <form method="post" action="{% url 'dashboard:delete' track.id %}"
                                  style="position:absolute; bottom: 0; left: 159px">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <input type="submit" class="btn btn-danger" value="Delete">
                                    </div>
                                </div>
                            </form>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    {% else %}#}
    {#        <h2 class="text-center mt-3">Please Sign</h2>#}
    {#    {% endif %}#}
{% endblock %}